title: RamaKrishna
logo: /assets/img/Rama.png
description: 
<a href="https://www.linkedin.com/in/rama-krishna-59898243/">LinkedIn</a>
<br>
<br>
This is RamaKrishna and I work in Dubai for a bank
theme: jekyll-theme-minimal
